---
title: "Lab5_individual"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
milk <- read.csv('state_milk_production.csv')
head(milk)
milk <- milk %>%
  mutate(milk_million = milk_produced/1000000)
```
#### Arie's Data
****
```{r}
milk1996 <- milk %>% filter(year == 1996) 
ggplot(data = milk1996 , mapping = aes(x = milk_million ))+
  geom_density()+
  ggtitle('Distribution of Milk Production in 1996')+
  xlab('Milk Produced(Millions lbs.)')+
  ylab('Density')

```
```{r}

milk1996 <- milk %>% filter(year == 1996) 
stat1996 <- milk1996 %>% summarise(average = mean(milk_million), med_1996= median(milk_million), max_produced = max(milk_million), min_produced = min(milk_million))

stat1996

```
```{r}

milk1997 <- milk %>% filter(year == 1997) 
stat1997 <- milk1997 %>% summarise(average = mean(milk_million), med_1997= median(milk_million), max_produced = max(milk_million), min_produced = min(milk_million))

stat1997

```
#### Anderson's Data
****
```{r}

milk1998 <- milk %>% filter(year == 1998) 
stat1998 <- milk1998 %>% summarise(average = mean(milk_million), med_1998= median(milk_million), max_produced = max(milk_million), min_produced = min(milk_million))

stat1998

max1998 <- milk1998 %>% top_n(1,milk_million)
max1998
min1998 <- milk1998 %>% top_n(-1,milk_million)
min1998

```
```{r}
ggplot(data = milk1998, mapping = aes(x = milk_million )) +
  geom_density() + 
  ggtitle('Estimation of milk produced in 1998') +
  xlab('Milk Produced') +
  ylab('Density')
```

```{r}
milk_production1998 <- milk1998 %>%
  group_by(state) %>%
  summarize(average = mean(milk_million), med_1998= median(milk_million), max_produced = max(milk_million), min_produced = (milk_million)) %>%
  as_tibble()
  
milk_production1998
```

#### Ethan's Data
****
* The mean and median millions of pounds of milk are 3251.8 and 1418, respectively, as shown in the first data frame.  California produces the most milk and Alaska produces the least amount of milk as shown in data frames two and three.
```{r, echo=FALSE}

milk1999 <- milk %>% filter(year == 1999) 
stat1999 <- milk1999 %>% summarise(average = mean(milk_million), med_1999= median(milk_million), max_produced = max(milk_million), min_produced = min(milk_million))

stat1999

max1999 <- milk1999 %>% top_n(1,milk_million)
max1999
min1999 <- milk1999 %>% top_n(-1,milk_million)
min1999


```
```{r}

milk2000 <- milk %>% filter(year == 2000) 
stat2000 <- milk2000 %>% summarise(average = mean(milk_million), med_2000= median(milk_million), max_produced = max(milk_million), min_produced = min(milk_million))

stat2000

max2000 <- milk2000 %>% top_n(1,milk_million)
max2000
min2000 <- milk2000 %>% top_n(-1,milk_million)
min2000

```
### Team Graph
****
```{r}

milksub <- milk %>%
  filter(state %in% c('Texas','Colorado','Connecticut', 'Alaska', 'California')) %>%
  select(state, year, milk_million)

ggplot(data = milksub, aes(x = year, y = milk_million, color = state)) +
  geom_boxplot() + 
  ggtitle('Milk Produced over time by State') +
  xlab('Year') +
  ylab('Milk Produced (Million lbs.)')

```


